### ISSUE TITLE
Beta number 1 is out!

### ISSUE THREAD

**Issue by remotevase** [MineCode-Devs/DevMine#1]
Hello everybody! Beta number 1 is out! Unfortunately, we already have major problems. Download the beta, unzip it, and run start.cmd. It will prompt you with an installer! Unfortunately, after entering the first value, it has a large error. Can anybody help me?

**Comment by MiroTheSuperDev** [comment]
can we start from the beginning

**Comment by MiroTheSuperDev** [comment]
just do it step by step from the beginning but on github

**Comment by remotevase** [comment]
Too hard.

**Comment by remotevase** [comment]
I think that I know a solution to this... Gonna try

**Comment by remotevase** [comment]
Beta number 2 is almost out! Current problem: Not loading. Nothing shows up in console, nothing loads.

**Comment by MiroTheSuperDev** [comment]
i think the problem with the not starting thingy is with php binary

**Comment by MiroTheSuperDev** [comment]
bin\php\php.exe: Exec format error
bin\php\php.exe: Exit 255

**Comment by MiroTheSuperDev** [comment]
it doesn't show me errors in php it show me that the bin is having problems

**Comment by Super35** [comment]
?

**Comment by Super35** [comment]
I'm on Mobile
PHP Stuff ?

**Comment by remotevase** [comment]
@AmiroEmad see new PHP binary (windows compatibility issues fixed)
