### ISSUE TITLE
New Issue when Starting the Server

### ISSUE THREAD

**Issue by remotevase** [MineCode-Devs/DevMine#13]
I got a ton done including updating DevMine back to 1.0. Now I get this:
```
Fatal error: Uncaught Error: Class 'DevMine\CompatibleClassLoader' not found in C:\Users\r_v\Documents\GitHub\DevMine\src\devmine\server\DevMine.php:97
Stack trace:
#0 {main}
  thrown in C:\Users\r_v\Documents\GitHub\DevMine\src\devmine\server\DevMine.php on line 97
bin\php\php.exe: Exit 255

**Comment by remotevase** [comment]
@Ad5001 @AmiroEmad @AppleDevelops @applqpak @Taki21 @TheDragonRing

**Comment by MiroTheSuperDev** [comment]
@I will fix this all I need to know where did you place CompatibleClassLoader.php

**Comment by MiroTheSuperDev** [comment]
The Class is located like that 

`require(\DevMine\PATH . "src/DevMine/CompatibleClassLoader.php");`



But when you go to src/DevMine/CompatibleClassLoader.php  there is no class named CompatibleClassLoader.php there

The problem is wrong destination

Here are the class names and the lines

"
```
-------------------------------------
src/devmine/server/Thread.php 

31				require(\DevMine\PATH . "src/DevMine/CompatibleClassLoader.php");
----------------------------------------------
src/devmine/server/Worker.php 


32				require(\DevMine\PATH . "src/DevMine/CompatibleClassLoader.php");
----------------------------------------------------
src/devmine/server/DevMine.php 


94			require_once(\DevMine\PATH . "src/DevMine/CompatibleClassLoader.php");
--------------------------------------
```
 "

**Comment by remotevase** [comment]
Oh, thanks so much, I'll try that now

**Comment by remotevase** [comment]
okay, syncing with github now

**Comment by remotevase** [comment]
Now I just gotta test some other stuff and then I'm good!

**Comment by remotevase** [comment]
New B2 is much better!
