### ISSUE TITLE
Error to Language

### ISSUE THREAD

**Issue by marcosvkp** [MineCode-Devs/DevMine#4]
'wmic' n▒o ▒ reconhecido como um comando interno
ou externo, um programa oper▒vel ou um arquivo em lotes.
[_] devmine set-up wizard
[_] Please select a language:
 English => eng
 简体中文 => chs
 繁體中文 => zho
 日本語 => jpn
 Русский => rus
[?] Language (eng): eng

Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src/devmine/languages/installer/,C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src/devmine/languages/installer/): O sistema n▒o pode encontrar o caminho especificado. (code: 3) in C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src\devmine\utilities\installer\InstallerLang.php:26
Stack trace:
#0 C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src\devmine\utilities\installer\InstallerLang.php(26): DirectoryIterator->__construct('C:\Users\ASUS\D...')
#1 C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src\devmine\utilities\installer\Installer.php(40): devmine\utilities\installer\InstallerLang->__construct('eng')
#2 C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src\devmine\server\DevMine.php(435): devmine\utilities\installer\Installer->__construct()
#3 {main}

  thr in C:\Users\ASUS\Downloads\PocketMine-Servers\DEVMINE\DEVMINE_B1\DEVMINE\src\devmine\utilities\installer\InstallerLang.php on line 26

**Comment by remotevase** [comment]
Yes. This is the issue with B1

**Comment by marcosvkp** [comment]
fix please? devmine is best to create plugins, much simple to use

**Comment by remotevase** [comment]
Yes. Will fix ASAP. May take up to a month, though...

**Comment by MiroTheSuperDev** [comment]
This problem has been fixed there is new errors now
