### ISSUE TITLE
Off-topic What is @TheProtest Doing

### ISSUE THREAD

**Issue by MiroTheSuperDev** [MineCode-Devs/DevMine#7]
![image](https://cloud.githubusercontent.com/assets/15315415/19397135/d7381916-9246-11e6-9774-310d964ae137.png)

The picture of email one shows his name but the log says this in both emails 

The message has been sent from 58.182.33.146 (Singapore) at 2016-10-06 06:25:46 on Android 4.4.2

Which means both are same persson

I just want to know why you hate me and what is the problem about me studying

**Comment by remotevase** [comment]
honestly, I have no idea...

**Comment by Taki21** [comment]
@TheProest35YT

**Comment by Super35** [comment]
My IP is 208.65.153.238

**Comment by Super35** [comment]
Not 58.182.33.146

**Comment by remotevase** [comment]
It changes

**Comment by Super35** [comment]
Wow
